//encapsullation _ exception

/*package OOPsConcepts;

import java.util.Scanner;

//exception handling
public class TryCatchBlockTest {
	Scanner in = new Scanner(System.in);
	//member variable
  //private int b = 10/2;
	 //private int[] b = {1, 2, 3, 4};
int b;
	//member function
 public void exceptionTest() {
	 System.out.println("enter value a");
	 int a = in.nextInt();
	 System.out.println("enter value b");
	 int b = in.nextInt();
	try { 
	    	 b = 10/0;
	    	System.out.println( "result" + b);
	 
	
	} catch(Exception e) {
		System.out.println("error"+e.getMessage());
	
		
 }finally {
	 System.out.println("program end");
	 
 }
 }
 
}
*/